name: Build and Deploy
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate Pages
        shell: pwsh
        run: |
          . ./.github/scripts/Set-Posts.ps1
      
      - name: Deploy
        uses: JamesIves/github-pages-deplopy-action@v4
        with:
          folder: posts
          branch: gh-pages
